git rm --cached **/**/**.tmp
git rm --cached **/**.tmp
git rm --cached **.tmp**
git rm --cached **/**/**.o
git rm --cached **/**.o
git rm --cached **.o
git rm --cached **.**.cmd
git rm --cached vmlinux
git rm --cached vmlinux.o
git rm --cached System.map
git rm --cached .missing-syscalls.d
git rm --cached .version
git rm --cached .tmp_versions
git rm --cached build
git rm --cached ./arch/arm64/dtb
git rm --cached ./arch/arm64/Image.gz
git rm --cached **/**.order
git rm --cached **/**/**/**.o
git rm --cached .config.old
git rm --cached **/**/**/**/**.o
git rm --cached */*/*/*.o
