git rm --cached **/**.tmp
git rm --cached **.tmp**
git rm --cached **/**.o
git rm --cached **.o
git rm --cached vmlinux
git rm --cached vmlinux.o
git rm --cached System.map
git rm --cached .missing-syscalls.d
gir rm --cached .version
git rm --cached .tmp_versions
git rm --cached build
